# Generated by Noturcode. Arguments not owned by Noturcode still use macOS netcat.
nc() {
  case "${1:-}" in
    ""|pair|ssh|resume|doctor|help|-h|--help)
      "$HOME/Library/Application Support/Noturcode/bin/noturcode-cli" "$@"
      ;;
    *)
      command /usr/bin/nc "$@"
      ;;
  esac
}
