#!/bin/zsh
set -euo pipefail

support_dir="$HOME/Library/Application Support/Noturcode"
bridge="$support_dir/bin/noturcode-bridge"
dry_run=false
delete_data=false

usage() {
  print "usage: $0 [--dry-run] [--keep-data|--delete-data]"
  print "  --dry-run      Show exactly what would change."
  print "  --keep-data     Preserve session state, logs, and existing backups (default)."
  print "  --delete-data   Also remove Noturcode's Application Support directory."
}

while (( $# > 0 )); do
  case "$1" in
    --dry-run) dry_run=true ;;
    --keep-data) delete_data=false ;;
    --delete-data) delete_data=true ;;
    -h|--help) usage; exit 0 ;;
    *) print -u2 "Unknown option: $1"; usage >&2; exit 64 ;;
  esac
  shift
done

command -v jq >/dev/null

backup_stamp=$(date +%Y%m%d-%H%M%S)
backup_root="$HOME/Library/Application Support/Noturcode Uninstall Backups/$backup_stamp"

announce() {
  if $dry_run; then
    print "would $*"
  else
    print "$*"
  fi
}

backup_file() {
  local target=$1
  [[ -f "$target" ]] || return 0
  local relative=${target#$HOME/}
  local backup="$backup_root/$relative"
  if $dry_run; then
    print "would back up $target -> $backup"
    return 0
  fi
  mkdir -p "${backup:h}"
  chmod 0700 "$backup_root" "${backup:h}" 2>/dev/null || true
  cp -p "$target" "$backup"
  print "backed up $target -> $backup"
}

remove_hook_command() {
  local target=$1
  [[ -f "$target" ]] || return 0
  local temporary
  temporary=$(mktemp)
  jq '
    .hooks = ((.hooks // {}) | with_entries(
      .value |= map(
        .hooks = ((.hooks // []) | map(
          select((((.command // "") | contains("noturcode-bridge"))) | not)
        ))
      ) |
      .value |= map(select(((.hooks // []) | length) > 0))
    ))
  ' "$target" > "$temporary"
  if cmp -s "$target" "$temporary"; then
    rm -f "$temporary"
    return 0
  fi
  backup_file "$target"
  announce "remove Noturcode hooks from $target"
  if ! $dry_run; then
    chmod 0600 "$temporary"
    mv "$temporary" "$target"
  else
    rm -f "$temporary"
  fi
}

remove_owned_file() {
  local target=$1
  local marker_a=$2
  local marker_b=$3
  [[ -f "$target" ]] || return 0
  if ! grep -Fq "$marker_a" "$target" || ! grep -Fq "$marker_b" "$target"; then
    print -u2 "preserved modified or unrecognized file: $target"
    return 0
  fi
  backup_file "$target"
  announce "remove $target"
  if ! $dry_run; then
    rm -f "$target"
  fi
}

remove_zsh_source() {
  local target="$HOME/.zshrc"
  local marker="# Noturcode interactive CLI"
  local source_line='[[ -r "$HOME/.config/noturcode/shell.zsh" ]] && source "$HOME/.config/noturcode/shell.zsh"'
  [[ -f "$target" ]] || return 0
  grep -Fq "$source_line" "$target" || return 0
  local temporary
  temporary=$(mktemp)
  awk -v marker="$marker" -v source_line="$source_line" \
    '$0 == marker || $0 == source_line { next } { print }' "$target" > "$temporary"
  backup_file "$target"
  announce "remove Noturcode shell source from $target"
  if ! $dry_run; then
    chmod 0600 "$temporary"
    mv "$temporary" "$target"
  else
    rm -f "$temporary"
  fi
}

remove_hook_command "$HOME/.claude/settings.json"
remove_hook_command "$HOME/.codex/hooks.json"
remove_hook_command "$HOME/.gemini/settings.json"

if [[ -d "$HOME/.hermes/plugins/noturcode" ]]; then
  hermes_bin=${commands[hermes]:-"$HOME/.local/bin/hermes"}
  if [[ -x "$hermes_bin" ]]; then
    backup_file "$HOME/.hermes/config.yaml"
    announce "disable the Noturcode Hermes plugin"
    if ! $dry_run; then
      HERMES_HOME="$HOME/.hermes" "$hermes_bin" plugins disable noturcode >/dev/null
    fi
  fi
fi
remove_owned_file "$HOME/.hermes/plugins/noturcode/plugin.yaml" \
  "name: noturcode" "Report local Hermes Agent session state"
remove_owned_file "$HOME/.hermes/plugins/noturcode/__init__.py" \
  "Noturcode integration for local Hermes Agent" "_SOURCE = \"hermes\""
remove_owned_file "$HOME/.config/opencode/plugins/noturcode.js" \
  "Generated by Noturcode" "noturcode-bridge"
remove_owned_file "$HOME/.pi/agent/extensions/noturcode.ts" \
  "Generated into Pi and OMP" 'const source = "pi"'
remove_owned_file "$HOME/.omp/agent/extensions/noturcode.ts" \
  "Generated into Pi and OMP" 'const source = "omp"'
remove_owned_file "$HOME/.claude/skills/nc/SKILL.md" \
  "name: nc" "Noturcode macOS notch tracker"
remove_owned_file "$HOME/.claude/skills/noturcode-summary/SKILL.md" \
  "name: noturcode-summary" "# Noturcode summary"
remove_owned_file "$HOME/.codex/skills/noturcode-summary/SKILL.md" \
  "name: noturcode-summary" "# Noturcode summary"
remove_owned_file "$HOME/Library/Application Support/iTerm2/Scripts/AutoLaunch/Ask Noturcode.py" \
  "ro.noturcode.ask-selection" "noturcode-bridge"
remove_owned_file "$HOME/.config/noturcode/shell.zsh" \
  "Generated by Noturcode" "command /usr/bin/nc"
remove_owned_file "$support_dir/bin/noturcode-cli" \
  "Noturcode remote" "StreamLocalBindUnlink=yes"
remove_owned_file "$support_dir/remote/noturcode-agent.py" \
  "Zero-dependency Noturcode helper" "Hooks must fail open"
remove_owned_file "$support_dir/bin/iterm2-workspace.py" \
  "Snapshot and restore the full iTerm2 workspace" "iterm2-workspace.py snapshot"
remove_zsh_source

if [[ -f "$bridge" ]]; then
  backup_file "$bridge"
  announce "remove $bridge"
  if ! $dry_run; then
    rm -f "$bridge"
  fi
fi

if $delete_data; then
  expected="$HOME/Library/Application Support/Noturcode"
  if [[ "$support_dir" != "$expected" || "$support_dir" == "$HOME" || "$support_dir" == "/" ]]; then
    print -u2 "Refusing unsafe data path: $support_dir"
    exit 65
  fi
  if [[ -d "$support_dir" ]]; then
    announce "remove retained Noturcode data at $support_dir"
    if ! $dry_run; then
      /bin/rm -rf -- "$support_dir"
    fi
  fi
else
  print "kept Noturcode session state, logs, and backups in $support_dir"
fi

if ! $dry_run; then
  rmdir "$HOME/.claude/skills/nc" "$HOME/.claude/skills/noturcode-summary" \
    "$HOME/.codex/skills/noturcode-summary" "$HOME/.pi/agent/extensions" \
    "$HOME/.omp/agent/extensions" "$HOME/.hermes/plugins/noturcode" \
    "$HOME/.config/opencode/plugins" \
    "$HOME/Library/Application Support/iTerm2/Scripts/AutoLaunch" 2>/dev/null || true
fi

print "Noturcode integrations were removed without stopping any terminal or harness session."
print "Restart iTerm2 later to unload the removed context-menu provider; no restart was performed."
if [[ -d "$backup_root" ]]; then
  print "uninstall backup: $backup_root"
fi
